### ISSUE TITLE
excessive time for cryptol_load with concatenation

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#103]
File 'cat20.cry' looks like this:

    x = [0] # [0] # [0] # [0] # [0] # [0] # [0] # [0] # [0] # [0] #
        [0] # [0] # [0] # [0] # [0] # [0] # [0] # [0] # [0] # [0]

... and cryptol :loads it just fine.  In saw:

    sawscript> time (cryptol_load "cat20.cry")
    Loading module Main
    Time: 58.031344s

It gets worse quickly, e.g. adding 4 more '# [0]':

    sawscript> time (cryptol_load "cat24.cry")
    Loading module Main
    Time: 466.528552s

Loading 'cat16' takes only 3.6s; 'cat12' takes 0.25s.  I did not have the patience to try 'cat32'.  None of these are a problem for cryptol.

**Comment by atomb** [comment]
I've been noticing a number of cases of slow translation between Cryptol and SAWCore. In many cases, I've assumed that it was truly stuck and wouldn't terminate. It's nice to have an example that's slow but actually does finish in a known amount of time.

**Comment by brianhuffman** [comment]
I did some digging and determined the source of the slowdown: It happens when the `importExpr` translation function encounters an `ECast` constructor. (In the type-checked Cryptol AST, `ECast` indicates a point in the typing derivation where the type is normalized, e.g. `[1 + 1 + 1][a]` is reduced to `[3][a]`.)

When we translate an `ECast`, the translator evaluates the two types involved to a normal form (using `scWhnf`) and checks whether they are alpha-equivalent. If not, then we must insert a SAWCore type coercion function (this indicates that the Cryptol typechecker has done some non-trivial reasoning on type equalities).

For some reason that I haven't figured out yet, reducing type expressions like `[1+1+1+1+1+...+1+1+1][a]` is taking an exponential amount of time. If we can fix this, then loading cryptol modules should be fast again.
