### ISSUE TITLE
exit doesn't exit

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#1173]
$ saw
     ┏━━━┓━━━┓━┓━┓━┓
     ┃ ━━┓ ╻ ┃ ┃ ┃ ┃
     ┣━━ ┃ ╻ ┃┓ ╻ ┏┛
     ┗━━━┛━┛━┛┗━┛━┛ version 0.7.0.99 (a923cfe3)

    sawscript> exit 0
    
    ExitSuccess
    sawscript> :h exit
    Description
    -----------

        exit : Int -> TopLevel ()

    Exit SAWScript, returning the supplied exit code to the parent
    process.
    sawscript>

**Comment by brianhuffman** [comment]
I guess the exception handler in the REPL casts its net just a bit too wide. I noticed recently that even panic messages are caught, and don't cause the REPL to exit.

We should probably add special cases to the REPL exception handler for the `ExitSuccess` and `ExitFailure` exceptions, so that `exit` will work as expected.

**Comment by brianhuffman** [comment]
I should also point out that `exit` does have the expected behavior when `saw` is run in batch mode.

**Comment by sauclovian-g** [comment]
actually n/m. Someone's fixed this; while the repl still traps panics, these days you can at least exit.
