### ISSUE TITLE
Make type constructors strict

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#1224]
I don't recall the context for this action item, but probably it has to do with squashing space leaks.

**Comment by brianhuffman** [comment]
The various type constructors are interpreted as strict in the saw-core simulator backends, and have been for some time. We can see this in the definition of the `TValue` type, where the arguments for vectors, arrays, pairs, and records are themselves fully-evaluated `TValue`s rather than thunks. https://github.com/GaloisInc/saw-script/blob/2e4fc0603da85bb1b188d4739a3386e25eea50ab/saw-core/src/Verifier/SAW/Simulator/Value.hs#L72-L83
