### ISSUE TITLE
encountered a bug in SawCore's implementation while using  `crucible_llvm_compositional_extract` 

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#1250]
I got this message while experimenting with the new `crucible_llvm_compositional_extract` function.  The example that generates it is way too big to post here.

    You have encountered a bug in SawCore's implementation.
    *** Please create an issue at https://github.com/GaloisInc/saw-core/issues

    %< --------------------------------------------------- 
      Revision:  d52a05c690929bd5ec9d9e27ef0f0674feca40d4
      Branch:    HEAD (uncommited files present)
      Location:  Verifier.SAW.Simulator.Value.toTValue
      Message:   Not a type value
    CallStack (from HasCallStack):
      panic, called at src/Verifier/SAW/Utils.hs:37:9 in saw-core-0.1-inplace:Verifier.SAW.Utils
      panic, called at src/Verifier/SAW/Simulator/Value.hs:141:14 in saw-core-0.1-inplace:Verifier.SAW.Simulator.Value
    %< ---------------------------------------------------

**Comment by RyanGlScott** [comment]
Unfortunately, I'm not sure that we can take action on this without a way to reproduce the error. Given how old this issue is (and that the context for triggering the original issue has likely evaporated by now), I'm going to close this, but please feel free to re-open this if you can provide instructions for how to trigger the issue.
