### ISSUE TITLE
User error on running saw with no parameters

### ISSUE THREAD

**Issue by daniel-vainsencher** [GaloisInc/saw-script#128]
Just running `saw` (or, also, running `saw ff_llvm.saw`) causes:

---

  / **|/ _' | | | |
  \** \ (_| | | | |
  |___/__,_|_,_/ version 0.2 (012a784)

Loading module Cryptol
saw: z3: runInteractiveProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

I installed from [1]. z3 isn't supposed to be an implicit dependency, right?

[1] https://github.com/GaloisInc/saw-script/releases/download/v0.2/saw-0.2-2016-04-12-Ubuntu14.04-64.tar.gz

**Comment by atomb** [comment]
Z3 actually is a strict dependency (because it's used in the type checker for Cryptol, which is a core component of SAW). I'm going to treat this ticket as a reminder to update the text on saw.galois.com to mention that.

It would also be good to improve that error message.

In principle, it might be possible to make some uses of SAW work without Z3. Much of the functionality wouldn't be available, but some features could be.

**Comment by daniel-vainsencher** [comment]
Thanks, I would expect to see this mentioned in Downloads, and possibly
also in the tutorial. Speaking of which, having found the tutorial on the
web, it is not obvious that the code directory is under doc, might be worth
removing that paper cut.

**Comment by tiziano88** [comment]
I was also confused by this and could not get things up and running out of the box. Would be good to mention this dependency somewhere.

**Comment by atomb** [comment]
With the latest updates to saw.galois.com and the README in this repo, I think this issue is resolved.
