### ISSUE TITLE
Constants involving ExtCns

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#1430]
The following operation makes sure to abstract a constant over any `ExtCns` values it mentions.  As I recall, this is done to make sure that the bodies of constants are in some sense "totally closed".  Is this restriction actually important/relied upon for anything we are doing? Would anything go wrong if we relaxed it? @brianhuffman 

https://github.com/GaloisInc/saw-script/blob/4222c6e44f1dd48c3f33c94a993a6d2aab1add46/saw-core/src/Verifier/SAW/SharedTerm.hs#L1453-L1471

I ask because it would be nice if we could allow Cryptol `primitive` declarations to be ultimately translated into Coq `Parameter` declarations, which would allow us to do proofs about operations that are held totally abstract. I have a branch that works in this direction and translates Cryptol `primitive` terms into `ExtCns`, which are then translated to Coq `Parameter` declarations.  So far so good.  However, any declarations that mention these primitives get turned into `Constant` terms which then are abstracted over all the ExtCns that they mention, and the declarations I wanted are now lambda-abstracted over the primitives instead of referencing them the way I wanted.

**Comment by brianhuffman** [comment]
As I recall, the abstracting over `ExtCns` variables was done to deal with a certain confusing situation that @atomb had encountered in some actual SAW proofs. What happened was that we had an `LLVMSetup` block that introduced some variables with `llvm_fresh_var` (thus producing `Term` values represented as `ExtCns`) and then within the same `LLVMSetup` block there was a `let {{ lhs = rhs }}` declaration that defined some other constants in terms of those variables.

Not only was this situation confusing, but I believe that it was actually unsound because when the override from such a proof was applied, it's supposed to do a substitution to replace the `ExtCns` variables from the `crucible_fresh_var` bindings with the values it was matched against. But they weren't being substituted because the occurrences were hidden inside a `Constant`. This led later to things being proved equal when they shouldn't have been.

**Comment by robdockins** [comment]
I see, so there's some mismatch between the contract of the `Constant` constructor (which is that terms with the same name are identical) and having `ExtCns` inside that are subject to substitution.

OK, I'll have to think some more about what is a good way to achieve what I want.
