### ISSUE TITLE
C static functions cannot be analyzed

### ISSUE THREAD

**Issue by robby-phd** [GaloisInc/saw-script#145]
SAW outputs "Bitcode file ....bc does not contain symbol ..." when analyzing static functions.
For example, the speck_encrypt and speck_decrypt of https://github.com/GaloisInc/saw-script/blob/702b1b839d0f81293dce331a27b4a80506265f82/examples/simon-speck/speck.c#L96-L111 were originally static functions and SAW could not locate them.

**Comment by atomb** [comment]
This appears to be an issue with `clang` removing unused static functions, rather than an issue in SAW. 

Consider this code:

~~~~ {.c}
static int f(int x) {
    return x;
}

int g(int x) {
    return f(x);
}
~~~~

If I compile it with `clang -c -emit-llvm` (using Clang 3.6), I get a bitcode file with two functions, defined as:

~~~~
define i32 @g(i32 %x) #0 {
...
}
~~~~

and

~~~~
define internal i32 @f(i32 %x) #0 {
...
}
~~~~

From `saw`, I can do:

~~~~
sawscript> m <- llvm_load_module "static.bc"
sawscript> m
Module: static.bc
Types:

Globals:

External references:

Definitions:
  i32 @g(i32 %x)
  internal i32 @f(i32 %x)


sawscript> gt <- llvm_extract m "g" llvm_pure;
sawscript> ft <- llvm_extract m "f" llvm_pure;
sawscript> print {{ gt zero }}
0
sawscript> print {{ ft zero }}
0
~~~~

So it looks like we're able to find `internal` functions. Can you check whether the generated bitcode file in that case actually includes the functions `speck_encrypt` and `speck_decrypt`?

**Comment by robby-phd** [comment]
Ah yes. I had to disable the function callers because SAW was throwing an error (https://github.com/GaloisInc/saw-script/blob/702b1b839d0f81293dce331a27b4a80506265f82/examples/simon-speck/speck.c#L114-L309;
see my comment at #141). I'm closing this issue since it is not actually a SAW problem.
