### ISSUE TITLE
toBool failed: <<fun>>

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#157]
```
import "3DES.cry";
time (prove_print (offline_smtlib2 "3DES_consistent_") {{ consistent }});
```
fails with
```
Proving 3DES consistency:
toBool failed: <<fun>>
```
However,
```
import "3DES.cry";
time (prove_print abc {{ consistent }});
```
works fine.

**Comment by weaversa** [comment]
There are plenty of these:
```
import "Salsa20.cry";
time (prove_print (offline_smtlib2 "Salsa20_has_no_collisions_") {{ Salsa20_has_no_collisions }});
```

**Comment by brianhuffman** [comment]
The `toBool` error indicates that saw-script has constructed a term that is not well-typed. This problem happens because our code to negate a predicate is horribly broken. (Particularly, function `negTerm` in module `SAWScript.Builtins`, which is used by all the `offline_*` proof tactics.) Unless the term is fully eta-expanded (i.e. it has explicit outermost lambdas for all function arguments) `negTerm` will put a `not` function in the wrong place.

As a workaround, you can eta-expand the predicates yourself:

    prove_print (offline_smtlib2 "3DES_consistent_") {{ \a b c d -> consistent a b c d }}
