### ISSUE TITLE
Invalid pointer operation (ptrtoint but cannot excute "urem")

### ISSUE THREAD

**Issue by Jerry-zhxf** [GaloisInc/saw-script#1603]
I want to calculate the begin address after the pointer memory alignment so I executed the following code.

```
uint8_t *p = ptr; 
(uint64_t *)((uintptr_t)p - (uintptr_t)p % alignment)
```

And then, I tried to use saw-script to run it, but I got a error (**Invalid pointer operation**).

```
Symbolic execution failed.
Abort due to assertion failure:
  memory_align.h:30:42: error: in PointerAligned
  Invalid pointer operation
  Operation: URem
  Value 1: $84
  Value 2: $85
```

And the llvm code is

```
%10 = load i8*, i8** %5, align 8, !dbg !4717
%11 = ptrtoint i8* %10 to i64, !dbg !4718
%12 = load i8*, i8** %5, align 8, !dbg !4719
%13 = ptrtoint i8* %12 to i64, !dbg !4720
%14 = load i64, i64* %4, align 8, !dbg !4721
%15 = urem i64 %13, %14, !dbg !4722
%16 = sub i64 %11, %15, !dbg !4723
%17 = inttoptr i64 %16 to i64*, !dbg !4724
```

I think it's done the pointer-to-integer forced conversion, so it should be correct to perform the modulo operation. 
What's the problem here? Also what do the variables $84 and $85 mean?

**Comment by robdockins** [comment]
Fundamentally, the problem here is a mismatch between the abstract memory model used by the verifier and the flat address space memory model that LLVM generally assumes. There's a lot of detail here I can go into, but the short version is that memory address in SAW are always considered as offsets from an abstract base pointer representing an allocation (stack variable, malloc call, etc.).  As a consequence, the only operations that are really allowed on pointers are the addition (or subtraction) of offset values.  It's quite difficult or impossible to give semantics to other operations.

Unfortunately, this means we have a lot of trouble reasoning about alignment tricks. We've discussed various ways to lift these restrictions, but they are all pretty complicated and haven't yet been implemented.

In this particular case, however, I'm reasonably confident that what you are trying to do is actually undefined behavior in C, as it would calculate a pointer value that is not contained in a valid allocation.

**Comment by sauclovian-g** [comment]
SAW is not intended to be able to handle this kind of pointer logic, whether or not it's formally defined behavior. I suspect that with more context we'd find that it is defined; the most common reason to do something like this with a subtraction is to align the stack pointer, and in that case, given some reasonable preconditions, the output pointer is still valid.

(Note that there's no guarantee in the standard that doing arithmetic on ```uintptr_t``` is equivalent to the same arithmetic on pointers, so the behavior is implementation-dependent, but I don't think LLVM supports implementations where the behavior isn't reasonable.)
