### ISSUE TITLE
[CI] Prelude.hs does not always rebuild when Prelude.sawcore is changed

### ISSUE THREAD

**Issue by m-yac** [GaloisInc/saw-script#1856]
I noticed while working on #1849 that it appears `Prelude.hs` does not always rebuild on CI when `Prelude.sawcore` is changed on the branch relative to `master`.

Specifically, it appears that every commit which does not itself change `Prelude.sawcore` or `Prelude.hs` uses a cached version of `Prelude.sawcore` from `master` – even when the branch as a whole relative to `master` does change `Prelude.sawcore`.

Here's the timeline of commits and CI passes/failures that makes me suspect this:
1. Commit 6d81c4475cf8fc0369b714144d06b85f9db2da5d changes `Prelude.sawcore` and `mr-solver-tests` such that `mr-solver-tests` will fail if the version of `Prelude.sawcore` from `master` is used
2. Commit c0f364cab2034fa5c33e43fedd1c20e52bc3232d does not change `Prelude.sawcore`, but also does not change `mr-solver-tests` in any way that should make it fail – however [`mr-solver-tests` fails](https://github.com/GaloisInc/saw-script/actions/runs/4569507302/jobs/8066575200)! The failure seems to indicate that the `saw` executable used for `mr-solver-tests` has the version of `Prelude.sawcore` from master (`test_fun0` was imported from `Prelude`).
3. Commit e99d03d956916937968216dfefef2a0be95ba067 changes `Prelude.sawcore` in a way which should have no impact on `mr-solver-tests`, but now [`mr-solver-tests` passes again](https://github.com/GaloisInc/saw-script/actions/runs/4569688792/jobs/8066784473)!
4. Commit b25fb57bc172aeb24c7f4715214b6229fe90981e (in a similar way to the one before last) does not change `Prelude.sawcore` or `mr-solver-tests`, but now [`mr-solver-tests` fails](https://github.com/GaloisInc/saw-script/actions/runs/4661413758/jobs/8251335639) – in the same way which indicates that the `Prelude.sawcore` used is the one from `master`.
5. I also tried making a commit which just makes a whitespace change to `Prelude.hs`, and the result was that [`mr-solver-tests` passes](https://github.com/GaloisInc/saw-script/actions/runs/4671065220/jobs/8272489302) (unfortunately I deleted this commit by force-pushing in an attempt to clean up the branch, but you can still see the CI run).

As I wrote all this out I realized that based on my hypothesis, the force-push cleanup I did will not actually work because I didn't change `Prelude.sawcore` or `Prelude.hs` in my last commit – so we'll see what happens.

Tagging @RyanGlScott and @kquick because I think maybe you guys are the CI guys? If not, let me know who I should ping!

**Comment by RyanGlScott** [comment]
I believe this is an unfortunate limitation of Template Haskell's ability to detect when files need to be recompiled. In particular:

* `Verifier.SAW.Prelude` uses Template Haskell to load `Prelude.sawcore`,
* CI builds `Verifier.SAW.Prelude` and caches the result, and
* If a subsequent commit changes `Prelude.sawcore`, GHC is likely not to notice the fact that `Verifier.SAW.Prelude` needs to be rebuilt.

I believe the typical way to work around this issue is by calling Template Haskell's [`addDependentFile`](https://hackage.haskell.org/package/template-haskell-2.19.0.0/docs/Language-Haskell-TH-Syntax.html#v:addDependentFile) function, which explicitly signals to GHC that the file using Template Haskell needs to be recompiled whenever the dependent file (in this case, `Prelude.sawcore`) is changed. This is the technique that libraries like [`file-embed`](https://hackage.haskell.org/package/file-embed) use, and it seems appropriate to mimic `file-embed` here.

**Comment by m-yac** [comment]
I did a bit of digging, and it looks like we actually do use (at least a version of) `addDependentFile`!

`Prelude.sawcore` gets [loaded by `defineModuleFromFileWithFns` in `Prelude.hs`](https://github.com/GaloisInc/saw-script/blob/239c50073e829ae2274338919f9665c0bd637481/saw-core/src/Verifier/SAW/Prelude.hs#L31), which [calls `defineModuleFromFile`](https://github.com/GaloisInc/saw-script/blob/239c50073e829ae2274338919f9665c0bd637481/saw-core/src/Verifier/SAW/ParserUtils.hs#L210), which [calls `addDep`](https://github.com/GaloisInc/saw-script/blob/239c50073e829ae2274338919f9665c0bd637481/saw-core/src/Verifier/SAW/ParserUtils.hs#L89), which finally [calls `qAddDependentFile`](https://github.com/GaloisInc/saw-script/blob/239c50073e829ae2274338919f9665c0bd637481/saw-core/src/Verifier/SAW/ParserUtils.hs#L79)! (Assuming the TH version is less than 2.7.0.)

This makes sense, because on my local machine, cabal does seem to always know to rebuild `Prelude.hs` when I change `Prelude.sawcore` – which seems to be the behavior you're talking about. On the other hand, it seems like the problem here is that when `Prelude.sawcore` *doesn't change* it uses an outdated version of the resulting `Prelude.hs` (i.e. one from `master`, not from the last commit on the branch).

**Comment by kquick** [comment]
My theory is that the main build is building saw and uploading it (https://github.com/GaloisInc/saw-script/blob/master/.github/workflows/ci.yml#L212), then the mr-solver-tests job is downloading that same artifact (https://github.com/GaloisInc/saw-script/blob/master/.github/workflows/ci.yml#L245).  If there were local changes, then saw gets rebuilt, overwriting that artifact and you get the good tests, but if there were no local changes, the artifact version runs.  Since the artifact name does not include the branch, you probably get the one uploaded from main (but who knows?).

To test this, I'd change the name (line 216, line 247, line 281, line 348, line 408, line 567, and anywhere else I missed) to include the branch (e.g. `name: "${{ runner.os }}-${{ github.ref_name }}-bins"`).

If the above fixes it for you, I think we definitely need it because it could be affecting other things here as well.

**Comment by RyanGlScott** [comment]
Unfortunately, these errors are now occurring on the `master` branch ([example](https://github.com/GaloisInc/saw-script/actions/runs/4735832209/jobs/8407636251#step:6:14)).

**Comment by m-yac** [comment]
Crap. Well maybe we ought to push a hotfix which changes the name of `test_fun0` in `mr_solver_tests` so it doesn't conflict with the `test_fun0` from the old version of `Prelude.sawcore`?

Of course there's still the deeper problem of why `saw` executable used during `mr_solver_tests` test is using the old version of `Prelude.sawcore` which defines a `test_fun0`. Now that this error is happening on `master` I really have no clue what could be happening...

**Comment by bboston7** [comment]
Just wanted to add as a datapoint that I've seen this issue locally of cabal not rebuilding the prelude when only `Prelude.sawcore` changes, so it's not purely a CI caching issue.

**Comment by bboston7** [comment]
A few other things I found:

* [It looks like `extra-source-file` in Cabal was broken until recently.](https://github.com/haskell/cabal/issues/8632)  Perhaps only some of us see this problem locally because we're running a Cabal version without the fix? It's not immediately clear to me which Cabal version includes the fix for this.
* There's a [long standing issue](https://github.com/haskell/cabal/issues/4746) that Cabal ignores `addDependentFile`

**Comment by RyanGlScott** [comment]
Interesting, I hadn't considered the possibility of this happening due to a `cabal` bug. We are currently using 3.8.1.0 in CI:

https://github.com/GaloisInc/saw-script/blob/fad48d8c04a5ea34268f05494e9dcb6aacfe1b0b/.github/workflows/ci.yml#L71

It might be worth bumping that to see if that makes a difference.

**Comment by bboston7** [comment]
Updating to `cabal-3.10.1.0` seems to have fixed the problem locally for me! It's worth a shot on the CI system.

**Comment by m-yac** [comment]
Testing in #1861!

**Comment by kquick** [comment]
That's unfortunate news about cabal, but I'm also worried that maybe we have two problems here: `cabal` issues and also my hypothesis about the archived binary we are using for these tests, so we should check into both.

**Comment by RyanGlScott** [comment]
After merging #1861, the CI for the `master` branch is now restored. I suppose it's still possible that there is some misconfiguration in our CI's use of `{upload,download}-action`, but the immediate issue appears to have been resolved. Would you be OK with closing this, @kquick?

**Comment by RyanGlScott** [comment]
After a discussion with @kquick, we've agreed that the primary issue (`Prelude.sawcore` modifications not triggering a rebuild) has been addressed, and as such, this issue can be closed.

@kquick is separately looking into whether the lack of branch information on the `download-artifact` could cause a job on a pull request to accidentally grab artifacts from a separate branch, and if this is the case, he will open a separate issue.
