### ISSUE TITLE
Parse error on `\n ->`

### ISSUE THREAD

**Issue by qsctr** [GaloisInc/saw-script#1894]
The specific sequence of characters `\n ->` fails to parse:
```
sawscript> (\n -> n) 1
Parse error at <stdin>:1:5-1:7: Unexpected `->'
```
however, the following works:
```
sawscript> (\x -> x) 1
[17:16:43.448] 1
sawscript> (\ n -> n) 1
[17:16:50.798] 1
```
Since only `\n` triggers this, I suspect the parser might be inappropriately recognizing the `\n` string escape sequence outside of a string literal.

**Comment by RyanGlScott** [comment]
@yav notes that this part of SAWScript's lexer looks very suspicious:

https://github.com/GaloisInc/saw-script/blob/0d6613fd82ce6197acbb2d226ab1e73623f5ff76/src/SAWScript/Lexer.x#L74

Due to the double quotes, this indicates a literal string match, and no escaping is done. In fact, we could probably delete this line, since `\n` is already included as a part of `$whitechar`:

https://github.com/GaloisInc/saw-script/blob/0d6613fd82ce6197acbb2d226ab1e73623f5ff76/src/SAWScript/Lexer.x#L28

(I'm unclear if that is sufficient to fix the bug at hand, but it definitely seems related.)
