### ISSUE TITLE
panic, called at src/Cryptol/TypeCheck/TypeOf.hs:65:24 in cryptol-3.1.0-inplace:Cryptol.TypeCheck.TypeOf

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#2043]
This happened when SAW `prove_print`ing a Cryptol property that uses numeric constraint guards.

**Comment by RyanGlScott** [comment]
I might need some more insight in order to reproduce this issue, as my attempts to do so have been unsuccessful thus far. I am trying something akin to:

```
// Test.cry
f : {n} [n]
f | n == 1 => zero
  | n != 1 => zero
```
```
// test.saw
import "Test.cry";

prove_print z3 {{ f`{2} == zero }};
```

But that verifies without issue, so this example must be too simplistic. Are you able to submit a minimal example of the how to trigger the panic?

**Comment by RyanGlScott** [comment]
Alright, here is a minimal reproduction of the issue:

```
// A.cry
module A where

parameter
  type N : #
  foo : [N]

bar : {n, a} (Zero a) => [n]a
bar | n == 1 => zero
    | n != 1 => zero
```
```
// B.cry
module B where

import `A as A

b : {n, a} (Zero a) => [n]a
b = A::bar`{32} { foo = zero }
```
```
// test.saw
import "B.cry";
```
```
$ ~/Software/saw-1.1/bin/saw test.saw
[14:08:54.071] Loading file "/home/ryanscott/Documents/Hacking/SAW/test.saw"
[14:08:54.098] You have encountered a bug in Cryptol's implementation.
*** Please create an issue at https://github.com/GaloisInc/cryptol/issues

%< ---------------------------------------------------
  Revision:  65397a491bddc3b4e8f41053106ce8859387d662
  Branch:    HEAD
  Location:  Cryptol.TypeCheck.TypeOf.fastTypeOf
  Message:   unexpected polymorphic type in expression:
             B::import of A at B.cry:4:1--4:15::bar(n != 1) N`1237 n`1233 a`1234 <>
             with schema:
             (n`1233 != 1) => {foo : [N`1237]} -> [n`1233]a`1234
CallStack (from HasCallStack):
  panic, called at src/Cryptol/Utils/Panic.hs:21:9 in cryptol-3.1.0-inplace:Cryptol.Utils.Panic
  panic, called at src/Cryptol/TypeCheck/TypeOf.hs:65:24 in cryptol-3.1.0-inplace:Cryptol.TypeCheck.TypeOf
%< ---------------------------------------------------
```

My hunch is that this is caused by this case of `importExpr'`:

https://github.com/GaloisInc/saw-script/blob/d56bc186983c4ed071c3cfe97fc9904830f64673/cryptol-saw-core/src/Verifier/SAW/Cryptol.hs#L1275

I think we need to implement this case explicitly, similarly to how https://github.com/GaloisInc/saw-script/pull/1911 implemented the [`importExpr` case for `EPropGuards`](https://github.com/GaloisInc/saw-script/blob/d56bc186983c4ed071c3cfe97fc9904830f64673/cryptol-saw-core/src/Verifier/SAW/Cryptol.hs#L1147-L1154).

**Comment by RyanGlScott** [comment]
I've submitted a Cryptol-side fix in https://github.com/GaloisInc/cryptol/pull/1648. Once that lands, the last remaining step would be to bump SAW's `cryptol` submodule and add a SAW-specific regression test.
