### ISSUE TITLE
Polymorphic `case` or more `case*` commands

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/saw-script#208]
We have `caseProofResult` and `caseSatResult`.  I _think_ the structures returned by `crucible_llvm_verify` and `llvm_verify` (`CrucibleMethodSpec` and `LLVMMethodSpec`) are deserving of their own `case` expressions as well, but admit I don't know their internals.

**Comment by brianhuffman** [comment]
Neither `CrucibleMethodSpec` nor `LLVMMethodSpec` is a sum type; as implemented, they can only represent the result of a successful verification. If `llvm_verify` or `crucible_llvm_verify` can't verify a spec, they should just fail instead of returning anything.

The `prove` command does return a sum type: either "QED" or a counterexample. A counterexample is meaningful because there's one proof goal that was user-supplied. If `llvm_verify` or `crucible_llvm_verify` fails, what could we return? Those commands produce multiple machine-generated proof obligations, so it's not so obvious how to package up a counterexample in a meaningful way.

**Comment by siddharthist** [comment]
I think this has been addressed for now, feel free to reopen for more discussion if necessary.
