### ISSUE TITLE
examples/allsat is broken

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/saw-script#217]
Running the example:
```
$ saw example.saw
```
Results in the following error:
```
...
  Type mismatch:
    Expected type: ([10], [10], [10], [10])
    Inferred type: (([10], [10], [10], [10])))
```
There are also multiple "fixity" warnings that should probably be addressed.

**Comment by jpziegler** [comment]
This fixes it, but the tuple indexing doesn't seem right.
```
ec allsat_print p = do {
  r <- sat abc p;
  caseSatResult r
    (print "Done!")
    (\t -> do {
      let s = {{ t.0 }};
      print s;
      allsat_print {{ \x -> x != s /\ p x }};
    });
};
```

**Comment by atomb** [comment]
Since there may be more than one variable bound in the solution to a SAT query, I don't think there's a good way to get around `t` being a tuple in the above. Special-casing it to avoid a one-tuple would make other situations less consistent. So, as awkward as it is, I think the fixed version you mention is a workable solution.
