### ISSUE TITLE
EasyCrypt

### ISSUE THREAD

**Issue by Johanvdberg** [GaloisInc/saw-script#231]
Hallo,

I see references to EasyCrypt. What is the plans for EasyCrypt?

**Comment by atomb** [comment]
We're in the process of translating SAWCore (SAW's internal language) into EasyCrypt function definitions. Since we can translate Cryptol to SAWCore, that'll allow us to use EasyCrypt to prove cryptographic properties about Cryptol functions. The work is still in early stages, though. See the `easycrypt` branch and the https://github.com/galoisinc/saw-core-easycrypt repository.

**Comment by Johanvdberg** [comment]
Does there exist any recommended reading?

**Comment by atomb** [comment]
There isn't any documentation on our code yet, but you can find out more about EasyCrypt at https://www.easycrypt.info/. You can find a tutorial, a reference manual, and material from various talks and courses there.

**Comment by Johanvdberg** [comment]
Will it be possible to use you algorithm specification in cryptol to prove properties about it in easycrypt?

**Comment by atomb** [comment]
That's the goal! Soon we should be able to show examples of how that works, and have a better sense for how easy it is.
