### ISSUE TITLE
struct of just one element

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#254]
When creating a crucible setup block using a C struct that has only one element, e.g.

In C:
```
typedef struct {
   uint32_t x;
} a_t;
```

In SAW:
```
let p_a <- crucible_alloc (llvm_struct struct.a_t);
...
crucible_execute [...];
...
crucible_points_to p_a (crucible_term {{ 10 : [32] }});
};
```

When running `saw` I get
```
types not memory-compatible
{ [12 x i32] }
[12 x i32]
```

I think his has to do with `llvm_struct`s producing tuples, and `cryptol` not having a 1-element tuple type (or does it???). Also, the curly braces are confusing, it makes native Cryptol users thing `llvm_struct` creates records. So, the error statement could be improved.

Note, if we change things to:
```
typedef struct {
   uint32_t x;
   uint32_t y;
} a_t;
```
and
```
let p_a <- crucible_alloc (llvm_struct struct.a_t);
...
crucible_execute [...];
...
crucible_points_to p_a (crucible_term {{ (10 : [32], 11 : [32]) }});
};
```
everything works fine.

**Comment by robdockins** [comment]
Interesting.  Clang is perfectly happy to coerce between a one-element struct and the type of its contained element.  Indeed, it seems to do this pretty aggressively.  A function declared as
```
typedef struct {
  uint32_t x;
} a_t;

uint32_t foo( a_t s ); 
```

Gets turned into:
```
define i32 @foo( i32 %s.coerce )
```

I guess we might have to add special cases for handling LLVM structs with 1 element... maybe also for empty structs.

**Comment by robdockins** [comment]
Ugh... clang will also just elide empty structs from the argument list, changing the arity of the function.  It will also turn functions that return an empty struct into `void` returns.

**Comment by TomMD** [comment]
Time for a higher level C-to-crucible backend?

**Comment by jpziegler** [comment]
This is an LLVM verifier, not a C verifier. So if Clang chooses to change
the type of a function, that should be what the user needs to deal with.
From that perspective, we need good tools guiding the user when they
encounter these sorts of things.

**Comment by robdockins** [comment]
I agree with @jpziegler on this point; we should help the user when these sorts of situations arise, by modifying error messages to suggest courses of action.

The immediate solution is to use the `crucible_struct` SAW combinator, which builds an LLVM struct from a list of field values.  E.g., I think the following modification will work:
```
crucible_points_to p_a ( crucible_struct [ crucible_term {{ 10 : [32] }} ] );
```

**Comment by robdockins** [comment]
Turns out, all the lower levels of the verification stack could handle memory compatibility of a one-element struct and it's member.  The only thing that was stopping this from working is an explicit check that was inserted to help users prevent mistakes.  I've relaxed this check now so that one-element structs are considered compatible with their field.

A more general solution is to use the `crucible_points_to_untyped` which skips the compatibility check altogether.

As to the other question about structs being passed as immediate (not via pointer) arguments... it turns out that clang applies the platform ABI rules to structure unpacking, so the resulting number of arguments to a function can very significantly from its apparent C type.  I don't know that there's a good way to navigate that except to have the user be aware of it.
