### ISSUE TITLE
Failing due to -Werror

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#27]
```
$ ./build-sandbox.sh -p
...
[2 of 2] Compiling Verifier.SAW.Cryptol ( src/Verifier/SAW/Cryptol.hs, dist/dist-sandbox-8e137b29/build/Verifier/SAW/Cryptol.o )

src/Verifier/SAW/Cryptol.hs:104:3: Warning:
    Pattern match(es) are non-exhaustive
    In a case alternative: Patterns not matched: C.TCLg2

<no location info>: 
Failing due to -Werror.
Failed to install cryptol-verifier-0.1
...
cabal: Error: some packages failed to install:
cryptol-verifier-0.1 failed during the building phase. The exception was:
ExitFailure 1
saw-script-0.1 depends on cryptol-verifier-0.1 which failed to install.
```

**Comment by ntc2** [comment]
This is weird: it appears your `deps/cryptol-verifier` and `deps/cryptol` repos are out of sync. Since you ran `build-sandbox.sh` with the `-p` option, this shouldn't be possible. The pattern in the error message was removed here (https://github.com/GaloisInc/cryptol-verifier/commit/2332ee38a23c95297622e72586b47b2bc769bc3by), because the corresponding constructor was recently removed from Cryptol.

**Comment by weaversa** [comment]
I deleted my cryptol 2 git repository, then recloned it and recompiled it. Then cleaned this saw-script directory and now everything builds fine.
