### ISSUE TITLE
ecdsa.saw error

### ISSUE THREAD

**Issue by semi-kim** [GaloisInc/saw-script#291]
Verifying mul_inner
saw: user error (Cryptol error:
[error] at ecdsa.saw: 289:42-289:48:
 Type mismatch:
    Expected type: Bit
    Inferred type : [32])

I just ran saw ecdsa. saw and I wonder if the saw script provided by Galois indicates an error.

What should I do?

---------------------------ecdsa.saw
282line 
azero <- java_var "azero" java_bool;

289line
let res - {{ mul_java::mul_java_inner (azero, a, ij, xi, yj, d) }};

**Comment by semi-kim** [comment]
saw-version is  2.0
saw is the latest version 
-----Original Message-----

**Comment by semi-kim** [comment]
https://github.com/GaloisInc/saw-script/commit/21008ee19ff7558cace437447bf1c393d9407fbb

Before the update --
Be well executed

**Comment by atomb** [comment]
The version of `ecdsa.saw` that comes with the released version of SAW 0.2 should work with that version. There have been quite a few changes to SAW since that release, though (and we're overdue for a new release), so the version of `ecdsa.saw` in the `master` branch on GitHub will only work with either the latest nightly pre-built version of SAW (see https://saw.galois.com/builds/nightly/) or with a SAW binary you build from source yourself.

**Comment by semi-kim** [comment]
I changed the saw to the latest version, so it works well.

Thank you so much!
