### ISSUE TITLE
Slowdown in compositional verification

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#306]
Commit 94663064bdeba4f9ed5fa6ead0cb2c0aa7cd9a44 causes a significant slowdown in compositional verification. The Salsa20 example goes from around 13s to longer than I have the patience to wait (more than several minutes).

**Comment by robdockins** [comment]
This issue has a temporary fix, which amounts to reverting the changes referenced above.

I suspect the issue is related to some values becoming symbolic under the new code paths, whereas they were previously concrete, which lead to symbolic nontermination.  I intend to continue investigating the issue.
