### ISSUE TITLE
typeOfSetupValue: non-representable type

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#329]
What about the type `bitvector_t` is non-representable?

```
let {{
  type uint64_t_list a = {nLength:[64], nLength_max:[64], pList:[a][64], nResizeAmt:[64]}
  type bitvector_t nBits = {nBits:[32], bits:uint64_t_list(nBits/^64)}
}};

let bitvector_t_alloc_spec = do {
  crucible_execute_func [crucible_term {{ 64 : [32] }}];
  crucible_return (crucible_term {{ zero : bitvector_t 64 }});
};

...

crucible_llvm_result <- crucible_llvm_verify bitvector_bc "bitvector_t_alloc" [] false bitvector_t_alloc_spec z3;
```

**Comment by brianhuffman** [comment]
Function `toLLVMType` in `CrucibleResolveSetupValue.hs`, which maps from Cryptol types to LLVM memory types, has an unimplemented case:
```
      Cryptol.TVRec _flds -> Nothing -- FIXME
```
Currently we represent Cryptol tuple types as LLVM struct types, with the fields in the same order. We could represent Cryptol record types the same way. However, the field ordering might be a bit unintuitive, because the Cryptol record fields have labels and LLVM struct fields don't. We could just put the Cryptol fields in alphabetical order, but that may or may not be what you want.

The nicest user experience would be to use a field ordering that matches the field names from the original C struct declaration. This would be a lot more work to implement, though, because the C field names aren't preserved in LLVM except in some optional debugging metadata. We'd have to figure out how to plumb that information around, and decide on a reasonable fallback behavior when it's not there or doesn't match up.

**Comment by brianhuffman** [comment]
A much easier fix would be to improve the error message, suggesting to use a tuple type instead of a record type.

**Comment by weaversa** [comment]
Thanks @brianhuffman 

I used tuples and now get this:

```
Incompatible types for return value when verifying bitvector_t_alloc
Expected: %struct.bitvector_t*
but given value of type: { i32, { i64, i64, [1 x i64], i64 } }
```

```
sawscript> bitvector_bc <- llvm_load_module "obj/bitvector.bc";
sawscript> print bitvector_bc 
Module: obj/bitvector.bc
Types:
  %struct.bitvector_t = type { i32, %struct.uint64_t_list }
  %struct.uint64_t_list = type { i64, i64, i64*, i64 }
```

Can you help with what is wrong now?

**Comment by brianhuffman** [comment]
You have an array type `[1 x i64]` in one, and a pointer type `i64*` in the other. Those are not memory-compatible in LLVM.

Unfortunately we don't yet have a way to use Cryptol to write any expressions involving pointer values. You'll probably need to use `crucible_points_to` with `crucible_elem`, etc. to specify the contents of the fields individually.

Also I just noticed something else: The error message says that you provided a struct value as the return type, while it expected a *pointer* to a struct. I think you'll need to have a line like `p <- crucible_alloc (llvm_struct "struct.bitvector_t")` immediately after the `crucible_execute_func`, and then change the last declaration to `crucible_return p`. (You'll probably also need a second `crucible_alloc` for the inner `i64*`.) Then you'll need something like `crucible_points_to p (crucible_struct [_, crucible_struct [_, _, _, _]])` to specify the contents of the allocated struct.

**Comment by weaversa** [comment]
I got it to work. For documentation, here's my solution. Thanks!

```
let bitvector_t_alloc_spec = do {

  crucible_execute_func [crucible_term {{ 64 : [32] }}];

  nLength <- crucible_fresh_var "bits->nLength" (llvm_int 64);
  nLength_max <- crucible_fresh_var "bits->nLength_max" (llvm_int 64);
  (List, pList) <- ptr_to_fresh "bits->pList" (llvm_array 1 (llvm_int 64));
  nResizeAmt <- crucible_fresh_var "bits->nResizeAmt" (llvm_int 64);

  nBits <- crucible_fresh_var "nBits" (llvm_int 32);

  pbv <- crucible_alloc (llvm_struct "struct.bitvector_t");
  crucible_points_to pbv (crucible_struct [crucible_term nBits,
    crucible_struct [
      crucible_term nLength,
      crucible_term nLength_max,
      pList,
      crucible_term nResizeAmt]]);

  crucible_return pbv;

  crucible_postcond {{ nBits == 64 }};
  crucible_postcond {{ nLength == 1 }};
  crucible_postcond {{ nLength_max == 1 }};
  crucible_postcond {{ List == [0] }};
};
```
