### ISSUE TITLE
realloc

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#331]
Would it be possible to add support for `realloc`?

```
Could not resolve function: realloc
```

**Comment by brianhuffman** [comment]
I think we could model `realloc` as just doing an `alloc`, a `memcpy`, and a `free`.  We'd need a way to determine the length argument for the `memcpy`, since that's not given as an argument to `realloc`, but we should be able to look that up in the `Mem` datatype.

So, yes, I think we could add support for `realloc` without too much trouble.

**Comment by robdockins** [comment]
`realloc` has some special cases regarding 0 size and null pointers, but I think it should be possible to handle these...

**Comment by robdockins** [comment]
Fixed as of: GaloisInc/crucible@afddfaff941a2e6af2342b9e4dd102bd244ee4bf
