### ISSUE TITLE
Symbolic execution failed, of table lookup

### ISSUE THREAD

**Issue by Johanvdberg** [GaloisInc/saw-script#342]
Verification of a table look up I got an error:

C Code:

    #include <stdint.h>
    uint8_t lookup[] = {0, 2, 4, 8};
    uint8_t do_look(uint8_t index) { return lookup[index % 4]; }

Saw script

    print "Compile the required C file, output: code.bc";
    exec "clang" ["-c", "-emit-llvm",  "-ocode.bc", "code.c"] "Create";
    print "Define the lookup specification";
    let look_setup = do {
        x <- crucible_fresh_var "x" (llvm_int 8);
        crucible_execute_func [crucible_term x];
        crucible_return (crucible_term {{ 2*(x % 4) }});
    };
    let main : TopLevel () = do {
        m <- llvm_load_module "code.bc";
        add_ms <- crucible_llvm_verify       // line 14
          m "do_look" [] false look_setup abc;
        print "Done.";
    };

The error I got is

    Loading file "lookup.saw"
    Compile the required C file, output: code.bc
    Define the lookup specification
    user error ("crucible_llvm_verify" (lookup.saw:14:15-14:35):
    Symbolic execution failed.
    Abort due to false assumption:
      Invalid memory load.
        address (2, bvSext 64 (bvSrem (bvZext 32 c@2:bv) 0x4:[32]))
        at type i8
      in do_look at internal
    Stack frame
      Allocations:
    
      Writes:
    
    Base memory
      Allocations:
        GlobalAlloc 2 0x4:[64] Mutable lookup
        GlobalAlloc 1 0x0:[64] Immutable do_look
      Writes:
    
    )
From the error  message I cannot see what is wrong. Verification should fail since `{{2*(x%4)}}` can be larger than `8`, but the error message talk about memory problems.

saw version: `0.2 (6c3ba709-dirty)`

**Comment by brianhuffman** [comment]
The memory trace in the error message shows no writes at all: In particular, the contents of the array `lookup` are uninitialized. This is why the read from `lookup` has failed. (The error message could certainly be better.) To fix this, you need to add a statement to the start of `look_setup`:
```
    crucible_points_to (crucible_global "lookup") (crucible_term {{ [0, 2, 4, 6] : [4][8] }});
```
For a mutable global, saw-script won't assume that it still has its initial value when a function is called, as it's value may have changed since initialization. You have to explicitly state any assumptions about the global's contents.

On the other hand, if you declare `lookup` as `const` in the C source, then you shouldn't need to specify its initial value in your spec. In that case, saw-script marks its memory region as immutable, and assumes that it will always contain the value it was initialized with.

We've also been talking about adding a setup command that lets you say essentially "global X has the same value it was initialized with", so you don't have to copy-and-paste the array value into your saw-script file. But we haven't implemented that feature yet.

**Comment by Johanvdberg** [comment]
Adding the `const` key word to the source is my preferred solution. It allow the compiler to check more condition that will help in ensuring quality of the code.

Use of a statement "global X has the same value it was initialized with" will be useful if working with a global values that is not constant but unmodified when some function is tested, in the larger program flow.

Will it be use full to use cryptol to some checks that compiler performs, e.g. an `const` value does not change? The only example that comes to mind is where a pointer to `const` values are cast so that the `const` condition falls away. This can be seed as bad program design but such situation are possible.

**Comment by robdockins** [comment]
Actually, we have a `crucible_global_initializer` setup value which fetches the initial value of the named global.  So, if you want to specify that a mutable global still has its initial value you can use:

```
crucible_points_to (crucible_global "glob") (crucible_global_initializer "glob")
```

As to the question about `const`, there are several uses of the const keyword in C.  One is for global variables, and allows the compiler to place the memory corresponding to that memory into read-only pages.  This information is retained through the LLVM frontend, and we can (and do) check that read-only global memory is never written.  Another use for `const` is in function arguments/local variables.  AFAIK, this really only exists so the compiler can pretty aggressively to constant propagation; these usually don't survive compilation because they are either propagated to use sites or promoted to global constants.  A third use is as a modifier to a pointer type.  This use is basically only advisory, as they can be removed by casts.

These second and third uses don't survive the clang front end; I'm pretty sure the LLVM bitcode has no notion of a `const` modifier for non-global variables.  So, there's nothing we can really in SAW about those kinds of idioms.

**Comment by siddharthist** [comment]
In case you haven't seen it, there is [a section in the SAW manual](https://github.com/GaloisInc/saw-script/blob/master/doc/manual/manual.md#global-variables) on the subject of Crucible/LLVM global variables. Unfortunately, it's not up on our website yet.

**Comment by Johanvdberg** [comment]
The example in the SAW manual creates `f_spec` and `g_spec` for

    int f(int y) {
      x = x + 1;
      return x + y;
    }

    int g(int z) {
      x = x + 2;
      return x + z;
    }

and it is the case that `f(g(z))=g(f(z)) + 1`, but the second definition of `f_spec` can only be used in be used in the `g(f(z))` part. Is it possible to keep track of changes made to global variable and use it to prove the `f(g(z))=g(f(z)) + 1` property?

**Comment by brianhuffman** [comment]
Yes, you can write a spec that allows for any initial value for the global variable. For example, you could use this spec for `f`:
```
f_spec <- crucible_llvm_verify m "f" [] true (do {
    x0 <- crucible_fresh_var "x0" (llvm_int 32);
    y <- crucible_fresh_var "y" (llvm_int 32);
    crucible_points_to (crucible_global "x") (crucible_term x0);
    crucible_execute_func [crucible_term y];
    crucible_return (crucible_term {{ 1 + x0 + y : [32] }});
    crucible_points_to (crucible_global "x") (crucible_term {{ x0 + 1 }});
}) abc;
```
The first `crucible_points_to` (in the pre-state section, before the `crucible_execute_func` command) binds the variable `x0` to the initial value of the global `x`. The second `crucible_points_to` (in the post-state section, after `crucible_execute_func`) specifies what the final value of the global `x` should be. Using this kind of spec, you should be able to verify functions  that call various combinations of `f` and `g`.

**Comment by brianhuffman** [comment]
To re-use the previously-proved `f_spec` and `g_spec`, you just need to include them in the list which is the third argument to `crucible_llvm_verify`:
```
fg_spec <- crucible_llvm_verify m "fg" [f_spec, g_spec] false (do {
  ...
```
Is this what you want, or have I misunderstood your question?

**Comment by Johanvdberg** [comment]
Yes, thanks you did answer my question.

**Comment by siddharthist** [comment]
It looks like all the questions here have been answered, feel free to re-open if that's not the case.
