### ISSUE TITLE
popcount not supported in SAWcore backend

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#345]
Now that crucible supports some of the LLVM popcount intrinsics, the problem has moved to SAWCore:

    AssumedFalse (AssumingNoError Unsupported feature: Expression form not yet implemented in SAWCore backend:
    bvPopcount 32 (bvZext 32 c@711:bv)

**Comment by robdockins** [comment]
I beleive this is fixed now as of 3a246c69f29e0217555dcf21b8d0fbb821d2a10c

**Comment by robdockins** [comment]
Is Z3 consuming CPU working on the problem when it hangs, or is the simulator still running?

I have a suspicion that using `toInteger` and `fromInteger` may be causing problems here.  The SMT encodings of these conversions are VERY expensive.  I'll poke around and see if I can pinpoint what's going on.

**Comment by msaaltink** [comment]
You are right about the integer conversion; redefining `wt`to work on finite types works fine.

**Comment by robdockins** [comment]
OK, that's good to know.  Yeah, anytime you're doing bitvector operations that operate at the bit level (rather than as arithmetic) it's probably going to be extremely inefficient to pass through the integer theory.  Even with just arithmetic, it's pretty dicey.  Unfortunately, SMTLib doesn't provide primitives for these conversions, so even easy cases involving trivial round-trips have to be bit-blasted into linear combinations of powers of 2 and the integer theory seems to have a really bad time with those...

I'm not sure why the first version of your verification above was so much faster, but it might be that we got lucky with some built-in rewrite rules and managed to eliminate the to/from integer conversion before encoding the problem.
