### ISSUE TITLE
memcpy and memory safety

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#373]
I'm confused by SAW's treatment of memcpy, which I naively like to think of as roughly equivalent to a loop that copies byte-by-byte  (so long as the memory regions do not overlap).  Here are two cases that violate the equivalence.

    #include <stdint.h>
    #include <string.h>

    void f(uint8_t *x) {
      uint8_t y[8];
      memcpy(x, y, 0);
    };

    void g(uint8_t *x) {
      uint8_t y[8];
      memcpy(x, y, 1);
    };

    void h(uint8_t *x) {
      uint8_t y[8];
      x[0] = y[0];
    };

In `f` there is a 0-length copy, which ought to do nothing, and so impose no conditions on memory (other than the blanket constraint on all library calls that the pointers are non-null). In `g` we copy 1 byte from an uninitialized memory region `y` into `x`, so that should fail.  `h` just spells it out for comparison.

Here's the SAWScript:

    m <- llvm_load_module "memcpy0.bc";

    let f_setup = do {
      xp <- crucible_alloc_readonly (llvm_array 4 (llvm_int 8));
      crucible_execute_func [xp];
      };

    // should succeed? And does in the 2018-10-23 nightly
    fails (crucible_llvm_verify m "f" [] false f_setup z3);

    let g_setup = do {
      xp <- crucible_alloc (llvm_array 4 (llvm_int 8));
      crucible_execute_func [xp];
      };

    // should fail?  y is uninitialized.
    crucible_llvm_verify m "g" [] false g_setup z3;

    fails (crucible_llvm_verify m "h" [] false g_setup z3); // as it should

In the `f_setup`, `x` points to read-only memory while in the `g_setup` it is writable.

I would have expected success for the first verification and failure for the others, whereas
in a recent SAW, all but the second fail.

**Comment by brianhuffman** [comment]
The behavior of `memcpy` is *not* the same as copying each byte in a loop: Instead of asserting that all source bytes are initialized, `memcpy` preserves the initialized/uninitialized status of each byte that it copies. So I'd expect function `g` to be well-defined, although reading from `x[0]` after the `memcpy` would be undefined.

I believe that this behavior is in accordance with the C standard, and in fact it is necessary to be able to copy e.g. an array of struct values that contain padding bytes.

As for the zero-size `memcpy`, I suppose we could add a special case so that we only require the target to be writable if the length is greater than 0.

**Comment by robdockins** [comment]
I'd just note that the C standard is a bit vague on this detail.  We've interpreted it in this way for essentially the reason @brianhuffman mentions.

Adding a special case for 0-length `memcpy` probably makes sense, although it's not completely clear to me how relaxed that special case should be... do the pointers need to be valid, even if not dereferenceable, or shall we allow dangling, or null pointers?

**Comment by msaaltink** [comment]
The C standard says all pointer arguments in library calls have to be valid, so I think null pointers are not allowed.

**Comment by robdockins** [comment]
After a bit of additional looking about, I found this sentence in C11, section 7.1.4:

> If an argument to a function has an invalid value (such as a value outside the domain of the function,
> or a pointer outside the address space of the program, or a null pointer, or a pointer to non-modifiable
> storage when the corresponding parameter is not const-qualified) or a type (after promotion) not
> expected by a function with variable number of arguments, the behavior is undefined.

The first (destination) argument to `memcpy` does not have the `const` qualifier, and I interpret this to mean that the destination pointer must be a non-null, live pointer to modifiable memory, even if the amount of memory to copy is 0.

As a result, the verification of `f` above fails (as it should).
Furthermore `g` succeeds because `memcpy` is allowed to copy uninitialized bytes.
However `h` fails because loading uninitialized bytes is _not_ allowed.
