### ISSUE TITLE
Improve REPL startup speed

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#394]
The SAW REPL currently type-checks the entire SAWCore prelude on startup, which takes a couple of seconds. Since it's linked in to the executable, it should be possible to do type checking during the Template Haskell splice that loads the file.

**Comment by brianhuffman** [comment]
I know that @eddywestbrook was planning something rather more complicated, but maybe pull request GaloisInc/saw-core#35 is enough on its own: On my machine, it reduces SAW startup time from 1.7s to 0.5s.

It turns out that most of the 1.7s startup was not spent type checking the prelude; rather, most of the time was spent calling `read` to parse the untyped module data structure (as I learned by running a profiling build of `saw`). My patch simply uses `TH.lift` on the untyped module instead of calling `read` at run-time on a string generated by calling `show` at compile time.

We may want to also do type checking at compile time (instead of just parsing) but it would bring only a small further improvement to startup time at the expense of possibly significant programming effort, and also an increase in code complexity. On the other hand, when working on the saw-core prelude, it sure would be nice to get type error messages at compile time instead of at run-time. Maybe we should just hold off on implementing that until someone thinks of an easy/simple way to implement it.

**Comment by atomb** [comment]
I'm going to close this and open another issue about type checking, since it's now a usability rather than a performance issue.
