### ISSUE TITLE
Type-check SAWCore prelude at compile time

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#446]
Currently, the SAWCore prelude is type-checked at startup, which can make it tedious to determine whether changes to the prelude are type-correct. Doing the type checking at compile time, which is possible with Template Haskell (and was done with earlier versions of SAWCore), would make development easier. It would also slightly improve the startup time of the SAWScript REPL (see #394).

**Comment by brianhuffman** [comment]
The saw-core prelude actually *is* type-checked at compile time; it has been since GaloisInc/saw-core#27. So if there is a type error we actually do get a compile-time failure. It just doesn't save the result of type checking, so the saw-core type checker also needs to run upon REPL startup. As of GaloisInc/saw-core#35, the saw-core prelude is at least *parsed* at compile time, which is the most expensive part.

As we get compile-time saw-core type errors and also reasonable start-up performance, I don't think we need to do anything else about this issue at the moment.
