### ISSUE TITLE
Unimplemented Primitives

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#62]
Would it be possible to implement the following primitives for use with the `llvm_symexec` command? I can provide `.bc` files and the saw-script that generates the error...just ask.
```
saw: user error (ERROR unimplemented primitives: Cryptol.arithBinaryBool Cryptol.arithUnaryBool Cryptol.bvLg2 Cryptol.ecError Cryptol.ecRandom Cryptol.lg2Nat)
```

**Comment by robdockins** [comment]
This looks like the same issue as #48.

Until a permanent fix is ready, I will simply downgrade this error to a warning.

**Comment by weaversa** [comment]
Thanks. I'll close this as a duplicate.

**Comment by weaversa** [comment]
So, what will happen once the errors are warnings? Could the symbolic simulation produce unsound results?

**Comment by robdockins** [comment]
No, this shouldn't be a soundness issue.

If one of the listed primitives is invoked during simulation, you'll get a runtime error.  The explicit check that is the source of this bug is a fail-fast check intended to notify developers that they forgot to hook up declared primitives to actual implementations.
