### ISSUE TITLE
writeSAIGInferLatches: domain or range not finite width:

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#66]
I'm pretty sure this function has both finite width range and domain, and matches the form.

```
Fstep : (Bit, [4]) -> (Bit, [4])
Fstep (x, is) = (accept, os)
  where
    os = [ False,
           (is@0 && x) || (is@1 && x),
       	   (is@0 && x) || (is@3 && x),
       	   (is@2 && ~x) ]
    accept = os@0 || os@1 || os@3
```
```
$ saw
   ___  __ _ _ _ _
  / __|/ _' | | | |
  \__ \ (_| | | | |
  |___/\__,_|\_,_/ 

Loading module Cryptol
sawscript> import "test.cry"
Loading module Main
sawscript> write_saig "F.aig" {{ Fstep }}

writeSAIGInferLatches: domain or range not finite width:
term must have type of the form '(i, s) -> (o, s)',
where 'i', 's', and 'o' are all fixed-width types,
but type of term is:
(Bit, [4]) -> (Bit, [4])
```

**Comment by weaversa** [comment]
Second attempt - this time with `write_saig'`:

```
Fstep' : [5] -> [5]
Fstep' x = [x']#s
  where (x', s) = Fstep (x@0, x@@([1..4]:[4][3]))
```
```
$ saw
   ___  __ _ _ _ _
  / __|/ _' | | | |
  \__ \ (_| | | | |
  |___/\__,_|\_,_/ 

Loading module Cryptol
sawscript> import "test.cry"
Loading module Main
sawscript> write_saig' "F.aig" {{ Fstep' }}
<<function>>
it : Term -> TopLevel ()
sawscript> write_saig' "F.aig" {{ 4 }} {{ Fstep' }}

Attempting to bitblast a term with a polymorphic type: {a} (fin a, a >= 3) => [a]
sawscript> write_saig' "F.aig" {{ 4:[3] }} {{ Fstep' }}

writeAIGComputedLatches:
non-integer or polymorphic number of latches;
you may need a width annotation '_:[width]':
value: <function>
term: Fstep'
type: [5] -> [5]
```

**Comment by weaversa** [comment]
The problem encountered with `write_saig'` might just be a documentation problem.
```
sawscript> :h write_saig'
<snip>
Arguments:
  file to translation to : String
  number of latches : Term
  function to translate to sequential AIG : Term
```
Swapping the order of Terms does produce an AIG with latches. So,
```
sawscript> write_saig' "F.aig" {{ Fstep' }} {{ 4:[3] }}
```
succeeds. However, I don't see why `4` needs to be typed.

**Comment by robdockins** [comment]
I've fixed the documentation for write_saig' and made it a little easier to use.

I also have tracked down the problem with write_saig; it has to do with the fact that we changed the representation of tuples and records, and some internal code is not recognizing the new pattern as a tuple type.

@brianhuffman, do you have an opinion on the best way to handle this problem? Essentially, it comes down to the fact that the `Cryptol.ty` sawcore function isn't being pushed down through the spine of the nested tuples, and the `asTupleType` recognizer doesn't realize that, e.g., `ty TCUnit` is convertable to the empty tuple `#()`.  The WHNF function is defined in terms of asTupleType, so it fails to help here.  Presumably we have the same problem with record types.

I think the easiest fix would be to rework scWhnf so it directly evaluates under the `PairValue` and `FieldType` constructors instead of using `asTupleType` and `asRecordType`.  I suppose we also need to evaluate down the spine of nested tuple and record values as well...

**Comment by brianhuffman** [comment]
@robdockins I agree that the best thing would be for `scWhnf` to avoid using `asTupleType` and `asRecordType`, and use the raw constructors instead. Also for normalization purposes, we should treat the "tail" fields of `PairValue` and `FieldValue` constructors as strict.

**Comment by brianhuffman** [comment]
I have now updated `scWhnf` in commit GaloisInc/saw-core@cd68b5e97f651479be02374158de374eae3ae69b.

@robdockins, can you check to see whether this fixes the problem you're seeing with `write_saig`?

**Comment by robdockins** [comment]
Indeed, that seems to have done the trick.
