### ISSUE TITLE
Simulation error: Invalid load address

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/saw-script#72]
I'm getting the error `Simulation error: Invalid load address`, followed by a successful proof :-)
See the example below:

```
$ more test.c
#include <stdint.h>

uint32_t sum(uint32_t *x) {
  uint32_t i=0, s=0;
  while(x[i] != 0) {
    s+=x[i++];
  }
  return s;
}

int main() {

  uint32_t x[5] = {1,2,3,4,0};
  uint32_t s = sum(x);
  printf("Sum is: %u\n", s);

  return 0;
}
```

```
$ more test.saw
let {{
  sum : {a} (fin a) => [a][32] -> [32]
  sum x = accums!0
    where accums = [0] # [ xi + a | xi <- x | a <- accums ]
}};

let sum_spec = do {
    x <- llvm_ptr "x" (llvm_array 10 (llvm_int 32));

    llvm_assert {{ [ xi == 0 | xi <- x ] == 1 }};

    llvm_return {{ sum x }};

    llvm_verify_tactic abc;
};

testbc <- llvm_load_module "test.bc";

sum_result <- llvm_verify testbc "sum" [] sum_spec;
```

```
$ ~/local/bin/clang test.c -c -emit-llvm -o test.bc
test.c:16:3: warning: implicitly declaring library function 'printf' with type 'int (const char *, ...)'
  printf("Sum is: %u\n", s);
  ^
test.c:16:3: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'
1 warning generated.
```

```
$ saw test.saw
Loading module Cryptol
Loading file "test.saw"
Simulation error: Invalid load address (Prelude.bvAdd
                        64
                        $alloc2
                        (Prelude.bvNat 64 40))
  at #10:@sum:%2.0:4
Successfully verified @sum
```

**Comment by atomb** [comment]
This is largely a usability issue, rather than a correctness/soundness one. Unfortunately, it's also a little deeply-intertwined in the symbolic execution process. What's going on here is that the condition provided by `llvm_assert` is used only in the final proof. It's never fed to the symbolic simulator. Once simulation finishes (including one path on which an out-of-bounds read occurred), the resulting term is proved equivalent to the spec under the assumption provided through `llvm_assert`. Because the failed path is infeasible under that assumption, the proof succeeds. So, the result it gives is correct (as you can see if you change the assertion to put a zero in the middle of the array, for instance, or if you don't constrain it at all), but obtained through an unsatisfying process.

It's going to take some refactoring to fix this in a nice way, so I'm going to remove the 0.2-alpha milestone.

**Comment by atomb** [comment]
This test works well with `crucible_llvm_verify` and we've just removed `llvm_verify`, so I'm going to close the issue.
