### ISSUE TITLE
saw: Bad uninterpreted constant name?

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/saw-script#75]
The C source:

    #include <stdint.h>
    #include <stdlib.h>
    uint64_t *make(uint64_t init) {
      uint64_t *r = malloc(sizeof(uint64_t));
      if (r==NULL) return r;
      *r = init;
      return r;
    }

and the SAW:

    c <- llvm_load_module "make.bc";
    i <- fresh_symbolic "i" {| [64] |};
    make <- llvm_symexec c "make" [] [("init", i, 1)] [("*return", 1)] false;
    prove cvc4 {{make == i}};

and the result:

    saw: Bad uninterpreted constant name: "$alloc4". Must be a valid identifier.

saw then conveniently exits.

This was an initial salvo into doing something with routines that return pointers.  What's the right way to handle that?  Is there anything I could put in a "llvm_return" line as part of a setup block for llvm_verify?

**Comment by atomb** [comment]
This is mostly fixed now: the fresh variables created for memory allocations used invalid identifiers from the SMT-Lib point of view.

However, there's another issue here. Depending on the result of `malloc`, the result of `make` will either be a pointer to `i` or `NULL`, which isn't always equal to `i`. If you remove the comparison with `NULL`, all provers can show that the theorem is valid (because the LLVM symbolic execution process considers the result of `malloc` to always be a valid pointer at the moment).

I'm leaving this ticket open for the moment because one strange thing remains: the SBV backend is giving empty counter-examples for this case. ABC correctly chooses an arbitrary value for `i`, and a value of 0 for the new pointer.

**Comment by brianhuffman** [comment]
I created a separate ticket for the remaining counterexample issue (#125), because it is has a completely different cause from the main part of this issue, and can be demonstrated with a much simpler example.
