### ISSUE TITLE
`eval_list` fails on the empty list

### ISSUE THREAD

**Issue by ChrisEPhifer** [GaloisInc/saw-script#783]
Consider the following SAWScript (note that `Bit` was chosen arbitrarily; any other monomorphization will also fail):

```
eval_list {{ [] : [0]Bit }};
```

This results in an error and crash: `saw: arithmetic underflow`.

**Comment by brianhuffman** [comment]
The problem is in the expression `traverse (scNat sc) [0 .. fromInteger n - 1]` in this line of code:
https://github.com/GaloisInc/saw-script/blob/263189284aa52fd859554c142197319c5e1eef67/src/SAWScript/Builtins.hs#L1167

Function `scNat` takes an argument of type `Natural`. The expression `[0 .. fromInteger n - 1]` is intended to evaluate to the empty list when `n = 0`, but it the upper bound `fromInteger 0 - 1` underflows on type `Natural`, yielding the error.

We could fix this by replacing `[0 .. fromInteger n - 1]` with `map fromInteger [0 .. n - 1]`.
