### ISSUE TITLE
Build fails on 32-bit CentOS 6

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/saw-script#96]
While building later packages we get the following error:

```
libabc.a: unknown symbol `__fixunssfdi'
ghc: unable to load package `abcBridge-0.16'
```

`__fixunssfdi` is floating-point conversion function, and a symbol that should be in `libgcc`, as I understand it.  I've no idea why it is being referenced or why it is not found.

**Comment by atomb** [comment]
I believe this is happening during Template Haskell expansion, so GHCi is trying to load the `abcBridge` package. GHCi currently uses its own, built-in proto-linker rather than the system linker. So the fact that it doesn't know to go look for `libgcc` isn't super surprising. How to work around it, though, and why it works on all the other platforms, I'm not sure.

I think these pages might be relevant:

https://ghc.haskell.org/trac/ghc/wiki/DynamicGhcPrograms
https://ghc.haskell.org/trac/ghc/wiki/DynamicLinkingDebate

In addition, this page suggests that the default behavior of the GHCi linker might be different on 32-bit Linux than it is on 64-bit Linux:

https://ghc.haskell.org/trac/ghc/wiki/DynamicByDefault

**Comment by atomb** [comment]
I managed to fix this by somewhat extensive refactoring to avoid the `jvm-verifier` library depending on `abcBridge` and avoiding Template Haskell in the `saw-script` package.
