### ISSUE TITLE
Remove dependency on jvm-verifier

### ISSUE THREAD

**Issue by atomb** [GaloisInc/saw-script#993]
Now that Crucible-based Java verification has better functionality and reasonable performance relative to `jvm-verifier` (e.g., see #399), it's getting close to time to cut the dependency on `jvm-verifier`.

**Comment by RyanGlScott** [comment]
I've found myself needing to change code in `jvm-verifier` recently, so naturally, this issue is relevant to my interests. Replacing all of `jvm-verifier` with `crucible-jvm` is a pretty tall order (at least for a neophyte like me), since the two libraries' APIs differ significantly in some places. Compare `jvm-verifier`'s [`runSimulator`](https://github.com/GaloisInc/jvm-verifier/blob/031561318c5ba932fb1201dddf3012ed4ccb708f/src/Verifier/Java/Simulator.hs#L423-L431) to `crucible-jvm`'s [`executeCrucibleJVM`](https://github.com/GaloisInc/crucible/blob/54bb819aa56fef20fe5deca4767bfcfc8f7d52e9/crucible-jvm/src/Lang/Crucible/JVM/Simulate.hs#L642-L652), for instance.

I was initially hopeful that I could get away with only replacing a small subset of `jvm-verifier`'s uses in SAW with `crucible-jvm`. The function from `jvm-verifier` I'm looking to change is [`tryLookupClass`](https://github.com/GaloisInc/jvm-verifier/blob/031561318c5ba932fb1201dddf3012ed4ccb708f/src/Verifier/Java/Codebase.hs#L117-L145), which has an [identical counterpart](https://github.com/GaloisInc/crucible/blob/8009c9c7b1eea030873aa3298e3fb39d34c15b56/crucible-jvm/src/Lang/JVM/Codebase.hs#L105-L133) in `crucible-jvm`. Unfortunately, it's not as simple as swapping out the former for the latter, since the two functions use different `Codebase` data types, so any function that depends on `tryLookupClass` would now need to be updated to use the `crucible-jvm` version of `Codebase`. I attempted to do this, but this following all of the dependencies eventually led me back to the use of `runSimulator`! I gave up at that point.

**Comment by brianhuffman** [comment]
One approach would be to start by removing all the deprecated `jvm-verifier`-based saw-script commands, and then proceed to remove all the dead code that results from that. Once all that stuff's gone, I imagine it would be a bit less work to remove the package dependency.

**Comment by brianhuffman** [comment]
#1005 removes the dependency of the `saw-script` and `saw-remote-api` packages on `jvm-verifier`. However, some of the integration tests (including `test0001`) rely on some java programs and `.jar` files that currently reside in the `jvm-verifier` repository. We'll need to decide what to do about that.

**Comment by kquick** [comment]
Plan: Remove JSS tests, and move jar files into saw repo examples directory.
